### ISSUE TITLE
Angular 10 Compatibility

### ISSUE THREAD

**Issue by auchEnia** [ui-router/angular-hybrid#445]
`error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).`

https://angular.io/guide/migration-module-with-providers

**Comment by christopherthielen** [comment]
Should be fixed by `@uirouter/angular` `6.0.3`.
I've also released a `@uirouter/angular-hybrid` `11.0.0` which has updated dependencies.

Let me know if this fixes it for you or not...

**Comment by auchEnia** [comment]
I have upgraded both packages, but it still doesn't work. The problem is a missing generic here https://github.com/ui-router/angular-hybrid/blob/master/src/angular-hybrid.ts#L214 and here https://github.com/ui-router/angular-hybrid/blob/master/src/angular-hybrid.ts#L221
