### ISSUE TITLE
"No provider for UrlService" error since version 3.1.3 (Angular CLI based app in AOT mode)

### ISSUE THREAD

**Issue by adamlubek** [ui-router/angular-hybrid#53]
I've got hybrid app based on Angular CLI. When running app in AOT mode (ng serve -o --aot=true) when this piece of code is run:

```
platformBrowserDynamic().bootstrapModule(AppModule)
  .then(platformRef => {
            const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
            upgrade.bootstrap(document.body, ['app'], {strictDi: false});

            const url: UrlService = platformRef.injector.get(UrlService);
            url.listen();
            url.sync();
    });

```

I am getting:
`
"Unhandled Promise rejection: No provider for UrlService! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for UrlService!"`

Both AOT/JIT version works fine with version 3.1.2. Version 3.1.3/3.1.4 works only in JIT mode.

**Comment by leosun1221** [comment]
Remove angular-ui-router (or @uirouter/angularjs) from your package.json and replace it with @uirouter/angular-hybrid. Add the @angular/* dependencies.

I removed those two then working:
@uirouter/angular": "^1.0.0-beta.7"
@uirouter/angularjs": "^1.0.6"

**Comment by adamlubek** [comment]
@leosun1221 I don't understand what you're talking about, Your comment seems incomplete. Which npm package do you mean by angular-ui-router? I've got @angular dependencies added, which exactly are you referencing? Also, I don't have any packages with versions you're referencing ("^1.0.0-beta.7", "^1.0.6"). 

Your comment isn't too helpful, can you clarify what you meant please?

**Comment by artaommahe** [comment]
@adamlubek also had this problem, this fixed my issue https://github.com/ui-router/sample-app-angular-hybrid/issues/8#issuecomment-322673416

**Comment by adamlubek** [comment]
@artaommahe so I changed code from:

```
    const url: UrlService = platformRef.injector.get(UrlService);

    url.listen();
    url.sync();
```
to
```

    const url: UrlService = getUIRouter(platformRef.injector).urlService;;

    url.listen();
    url.sync();
```

this compiles indeed but it completely breaks routing, states which were working aren't recognized anymore

**Comment by artaommahe** [comment]
@adamlubek i use it like so
```ts
deferAndSyncUiRouter(AppMainOldModule);

platformBrowserDynamic()
  .bootstrapModule(AppMainModule)
  .then(platformRef => bootstrapWithUiRouter(platformRef, AppMainOldModule));

export function deferAndSyncUiRouter(angularjsModule: ng.IModule): void {
  angularjsModule
    .config([ "$urlServiceProvider", ($urlServiceProvider: UrlRouterProvider) => $urlServiceProvider.deferIntercept()])
    .run(["$$angularInjector", $$angularInjector => {
      const url: UrlService = getUIRouter($$angularInjector).urlService;
      url.listen();
      url.sync();
    }]);
}

export function bootstrapWithUiRouter(platformRef: NgModuleRef<any>, angularjsModule: ng.IModule): void {
  const injector = platformRef.injector;
  const upgradeModule = injector.get(UpgradeModule);

  upgradeModule.bootstrap(document.body, [ angularjsModule.name ], { strictDi: true });
}
```

**Comment by adamlubek** [comment]
I've tried your code, routes are still dead :( the only difference is that I've got "$urlServiceProvider: UrlService" instead of "$urlServiceProvider: UrlRouterProvider" as I don't know where to import UrlRouterProvider from?

I'm running @angular/* version 4.4.2 if it makes any difference.

**Comment by yzabelin** [comment]
const $uiRouter: UIRouter = platformRef.injector.get(UIRouter );
const $urlService: URLService = $uiRouter.urlService;

**Comment by leosun1221** [comment]
@adamlubek  remove @uirouter/angular and @uirouter/angularjs in your package.json file, 
only use @uirouter/angular-hybrid 

I found this is the working example : https://github.com/ui-router/sample-app-angular-hybrid/tree/e4b1144d5e3e3451f0f0cc640175bb7055294fdd

**Comment by adamlubek** [comment]
@leosun1221 I don't have  'uirouter/angular' and 'uirouter/angularjs' in my package.json at all.

**Comment by rdukeshier** [comment]
I had the same issue.  Appears to be fixed in 3.1.7.

**Comment by christopherthielen** [comment]
> I had the same issue. Appears to be fixed in 3.1.7.

Hello all, is this still an issue or can I close this?  If it is an issue, can somebody show me how to reproduce it?

**Comment by jarregui** [comment]
I think it was fixed some time ago, I don't face it anymore

**Comment by adamlubek** [comment]
yes, it's all good now, thanks @christopherthielen

**Comment by httpete** [comment]
I am still seeing this problem with  @uirouter/angular-hybrid@3.1.8 and the Latest Angular 5.2.2

Unhandled Promise rejection: StaticInjectorError(RootModule)[UrlService]: 
  StaticInjectorError(Platform: core)[UrlService]: 
    NullInjectorError: No provider for UrlService! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError(RootModule)[UrlService]: 
  StaticInjectorError(Platform: core)[UrlService]:

**Comment by lamaan** [comment]
having the same problem too, comparing to the example, can we have this working in the latest angular framework please? (5.2.3)

**Comment by httpete** [comment]
There are complications when using npm linked file:.. local packages and Angular. I am finding that this webpack config fixes it. The key is the modules, it HAS to point all to the TOP node_modules, not a nested version.

`        resolve: {
            extensions: ['.ts', '.js'],
            modules: [
                path.resolve(path.join(__dirname, 'node_modules'))
            ],
            symlinks: true,
            mainFields: [
                "browser",
                "module",
                "main"
            ],
            alias: {

            }
        },`

**Comment by AlexSwensen** [comment]
@artaommahe that was a super helpful code snippet.

I modified it to the following:
```
angular.element(document).ready(() => {
  deferAndSyncUiRouter(angularJSAppModule);
  platformBrowserDynamic()
    // Manually bootstrap the Angular app
    .bootstrapModule(AppModule)
    .then(platformRef => bootstrapWithUiRouter(platformRef, angularJSAppModule));

});

export function deferAndSyncUiRouter(angularjsModule: ng.IModule): void {
  angularjsModule
    .config([ "$urlServiceProvider", ($urlService: UrlService) => $urlService.deferIntercept()])
    .run(["$$angularInjector", $$angularInjector => {
      const url: UrlService = getUIRouter($$angularInjector).urlService;
      url.listen();
      url.sync();
    }]);
}

export function bootstrapWithUiRouter(platformRef: NgModuleRef<any>, angularjsModule: ng.IModule): void {
  const injector = platformRef.injector;
  const upgradeModule = injector.get(UpgradeModule);

  upgradeModule.bootstrap(document.body, [ angularjsModule.name ]);
}
```

That got everything working for me.

**Comment by Jakobinec** [comment]
@AlexSwensen or @artaommahe
Could you tell me please what code should be in  AppModule.ts file (Angular module). If I use there code from documentation

```
const nestedState: NgHybridStateDeclaration = {
  url: '/angularRoute',
  name: 'angularRoute',
  component: UrlTestComponent,
};

@NgModule({
  declarations: [
    UrlTestComponent,
    AngularDowngradeTestComponent
  ],
  exports: [ AngularDowngradeTestComponent ],
  entryComponents: [AngularDowngradeTestComponent],
  imports: [
    BrowserModule,
    UpgradeModule,
    // UIRouterUpgradeModule.forRoot(),
    //UIRouterUpgradeModule.forChild(StaticPagesRoutes)
    UIRouterUpgradeModule.forRoot({ states: [nestedState] }),
  ],
  providers: [],
})
export class AppModule 
{ 
  constructor(private upgrade: UpgradeModule) { }
  ngDoBootstrap() {
    setAngularJSGlobal(angular);
    this.upgrade.bootstrap(document.body, ['mainApp'], { strictDi: true });
  }
}
```

I have an error 'You try bootstrap application twise'

**Comment by christopherthielen** [comment]
For anyone coming to this issue looking to resolve the "no provider" errors, make sure that you do not have multiple copies of the `@uirouter/*` packages nested in your node_modules directory.  

One easy way to find out is to run these commands:

```
npm list @uirouter/core
```

```
npm list @uirouter/angular
```

```
npm list @uirouter/angularjs
```

```
npm list @uirouter/angular-hybrid
```

For each one, make sure there is only one version of the uirouter packages in the output.
